# Generated by Django 5.2 on 2025-05-14 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=100)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('pediatrician', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('birth_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mother_maiden_name', models.CharField(max_length=255)),
                ('birth_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('father_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHospitalizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OUT PATIENT', 'Out patient'), ('IN PATIENT', 'In patient')], max_length=20, null=True)),
                ('name_of_facility', models.CharField(max_length=200)),
                ('date_of_visit', models.DateField()),
                ('name_of_physician', models.CharField(max_length=200)),
                ('chief_complaint', models.CharField(max_length=200)),
                ('nurses_notes', models.TextField(blank=True, null=True)),
                ('medical_impression', models.CharField(max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TinyLog.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ImmunizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('vaccine_batch_number', models.CharField(max_length=50)),
                ('date_of_administration', models.DateField()),
                ('facility_name', models.CharField(max_length=255)),
                ('administering_provider', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TinyLog.patient')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Healthcare Provider', max_length=100)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
